title: "Ğ’Ñ‹Ğ±ĞµÑ€ĞµÑ‚Ğµ Ğ¡ĞµÑ‚ÑŒ!"
subtitle: "Ğ’Ñ‹Ğ±ĞµÑ€Ğ¸Ñ‚Ğµ Ğ¾Ğ¿Ñ†Ğ¸Ñ Ğ½Ğ¸Ğ¶Ğµ:"
buttons:
  - text: "Mainnets ğŸ’µ"
    callback: "open_network_menu:mainnet"
  - text: "Testnets âŒ›"
    callback: "open_network_menu:testnet"
  - text: "ğŸ’ ĞĞ°Ğ·Ğ°Ğ´"
    callback: "go_back"