title: "Ğ’Ñ‹Ğ±ĞµÑ€ĞµÑ‚Ğµ Ğ¡ĞµÑ‚ÑŒ Ğ´Ğ»Ñ Ğ¿Ñ€Ğ¾Ğ²ĞµÑ€ĞºĞ¸ NFT"
subtitle: "&lt;=====3"
buttons:
  - text: "Mainnets ğŸ’µ"
    callback: "open_network_menu:mainnet"
  - text: "Testnets âŒ›"
    callback: "open_network_menu:testnet"
  - text: "ğŸ’ ĞĞ°Ğ·Ğ°Ğ´"
    callback: "go_back"