title: "ะัะฑะตัะตัะต ะัะพะตะบั ะดะปั ะฟัะพะฒะตัะบะธ ะะบัะธะฒะฝะพััะธ"
subtitle: ""
buttons:
  - text: "Monad ๐พ"
    callback: "monad_check_activity"
  - text: "Eclipse ๐ฎ"
    callback: "eclipse_check_activity"
  - text: "๐ ะะฐะทะฐะด"
    callback: "go_back"