title: "Ğ’Ñ‹Ğ±ĞµÑ€ĞµÑ‚Ğµ Ğ¡ĞµÑ‚ÑŒ!"
subtitle: "Ğ’Ñ‹Ğ±ĞµÑ€Ğ¸Ñ‚Ğµ Ğ¾Ğ¿Ñ†Ğ¸Ñ Ğ½Ğ¸Ğ¶Ğµ:"
buttons:
  - text: "Base ğŸ’™"
    callback: "base_network_balance"
  - text: "Arbitrum ğŸ©µ"
    callback: "arb_network_balance"
  - text: "ğŸ’ ĞĞ°Ğ·Ğ°Ğ´"
    callback: "go_back"