title: "Ğ’Ñ‹Ğ±ĞµÑ€ĞµÑ‚Ğµ Ğ¡ĞµÑ‚ÑŒ!"
subtitle: "Ğ’Ñ‹Ğ±ĞµÑ€Ğ¸Ñ‚Ğµ Ğ¾Ğ¿Ñ†Ğ¸Ñ Ğ½Ğ¸Ğ¶Ğµ:"
buttons:
  - text: "Monad ğŸ‘¾"
    callback: "monad"
  - text: "Sahara ğŸœï¸"
    callback: "sahara"
  - text: "ğŸ’ ĞĞ°Ğ·Ğ°Ğ´"
    callback: "go_back"